site_name: Axxes Traineeship
repo_url: https://github.com/RobKenis/traineeship
repo_name: RobKenis/traineeship
plugins:
  - search
  - awesome-pages
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs