---
Description: Prometheus with Grafana
Resources:
  Prometheus:
    Type: AWS::APS::Workspace
    Properties:
      Alias: TestWorkspace
  AmazonGrafanaWorkspaceIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonPrometheusQueryAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  Grafana:
    Type: 'AWS::Grafana::Workspace'
    Properties:
      AccountAccessType: CURRENT_ACCOUNT
      Name: AmazonGrafanaWorkspace
      Description: Amazon Grafana Workspace
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: CUSTOMER_MANAGED
      GrafanaVersion: '9.4'
      RoleArn: !GetAtt AmazonGrafanaWorkspaceIAMRole.Arn